---
services:
  database:
    image: mysql:8.3
    container_name: regina_db_mysql
    ports:
      - 3333:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_MASTER_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - CONTAINER_ROLE=app
    volumes:
      - db-data:/var/lib/mysql
      - ~/php.ini:/usr/local/etc/php/php.ini
    networks:
      - mysql_network

  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV="${APP_ENV}"
    container_name: regina_laravel_app
    environment:
      - APP_ENV="${APP_ENV}"
      - CONTAINER_ROLE=app
    working_dir: /var/www
    ports:
      - 8010:8000
    depends_on:
      - database
    networks:
      - mysql_network


  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
          - 9000:80
      environment:
          - PMA_ARBITRARY=1
          - UPLOAD_LIMIT= 100000000
      depends_on:
          - database
      networks:
        - mysql_network


volumes:
  db-data: null

networks:
  mysql_network:
      external: true
