---
version: "3.8"
services:
  database:
    image: mariadb:10.6
    container_name: regina_db_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}


    volumes:
      - db-data:/var/lib/mysql
      - ~/php.ini:/usr/local/etc/php/php.ini
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV="${APP_ENV}"
    container_name: regina_laravel_app
    environment:
      - APP_ENV="${APP_ENV}"
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8010:8000
    depends_on:
      - database
volumes:
  db-data: null

