---
version: "3.8"
services:
  database:
    image: mysql:8.2
    container_name: regina_db_mysql
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=samson
      - MYSQL_USER=sam
      - MYSQL_PASSWORD=samson
      - CONTAINER_ROLE=app
    volumes:
      - db-data:/var/lib/mysql
      - ~/php.ini:/usr/local/etc/php/php.ini
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV="${APP_ENV}"
    container_name: regina_laravel_app
    environment:
      - APP_ENV="${APP_ENV}"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8010:8000
    depends_on:
      - database

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
          - 9000:80
      environment:
          - PMA_ARBITRARY=1
          - UPLOAD_LIMIT= 100000000
      depends_on:
          - database
volumes:
  db-data: null

