version: '3'

services:
    mysql_db:
        image: mysql:8.3
        container_name: regina_prod_mysql
        restart: unless-stopped
        ports:
            - 3361:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_MASTER_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_INITDB_ARGS="--default-authentication-plugin=mysql_native_password"
        volumes:
            - db-data:/var/lib/mysql
            - ~/php.ini:/usr/local/etc/php/php.ini
            - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        networks:
            - mysql_network

    regina_app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_ENV="${APP_ENV}"
        container_name: regina_laravel_app
        environment:
            - APP_ENV="${APP_ENV}"
            - DB_DATABASE=${DB_DATABASE}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_USERNAME=${DB_USERNAME}
            - CONTAINER_ROLE=app
            - UPLOAD_LIMIT=100000000
            - PHP_UPLOAD_MAX_FILESIZE=20M
            - PHP_POST_MAX_SIZE=20M
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8050:8000
        depends_on:
            - mysql_db
            - redis  # Added Redis dependency for the app
        networks:
            - mysql_network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9300:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=100000000
        depends_on:
            - mysql_db
        networks:
            - mysql_network

    redis:
        image: redis:alpine  # Added Redis service
        container_name: regina_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - mysql_network

    queue_worker:
        build:
            context: .  # Build the image from the Dockerfile in the current directory
            dockerfile: Dockerfile # Use the Laravel app container for queue worker
        container_name: regina_queue_worker
        command: queue_worker  # Tells entrypoint.sh to start the queue worker
        depends_on:
            - redis
            - mysql_db
            - regina_app
        networks:
            - mysql_network


    horizon:
        build:
            context: .  # Build the image from the Dockerfile in the current directory
            dockerfile: Dockerfile
        container_name: laravel-horizon
        volumes:
            - .:/app
        depends_on:
            - redis
        networks:
            - mysql_network
volumes:
    db-data: null

networks:
    mysql_network:
        driver: bridge
