---
services:
  backend:
    image:  "${DOCKER_USERNAME}/${DEV_IMAGE_NAME}:${DEV_IMAGE_TAG}"
    container_name: regina_laravel_app
    environment:
      - APP_ENV="${APP_ENV}"
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - CONTAINER_ROLE=app
    working_dir: /app
    ports:
      - 8030:8000
    networks:
      - web_mysql_network

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
          - 9300:80
      environment:
          - PMA_ARBITRARY=1
          - UPLOAD_LIMIT= 100000000
      networks:
        - web_mysql_network
volumes:
  db-data: null

networks:
  web_mysql_network:
    external: true 
