name: CI - Development

on:
  push:
    branches:
      - develop   # Trigger on push to the develop branch
  pull_request:
    branches:
      - develop   # Trigger on pull requests targeting the develop branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      IMAGE_NAME: oshabz/regina-backend-dev
      IMAGE_TAG: ${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t "$IMAGE_NAME:IMAGE_TAG" .

      - name: Push Docker image to development registry
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: $IMAGE_NAME:IMAGE_TAG